name: Docker # 名字随意

on:
  push: # push 到主分支自动发布
    branches: ["main"]
    paths-ignore: # 忽略一些不必要的文件
      - ".gitignore"
      - "README.md"
      - "README.linux.md"
      - "配置文件说明.md"
      - ".vscode/**"
      - ".img/**"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx # 设置 Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub # 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image to Docker Hub # 打包并推送镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            yydsxll/jctest:latest
            yydsxll/jctest:${{ github.run_id }}
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/arm/v7
